### ISSUE TITLE
Jetson Nano support

### ISSUE THREAD

**Issue by abhatikar** [alwaysai/spatial-ai-webinar-repo#4]
I am getting an error related to pycuda on jetson nano. Am I missing anything ?
thanks
```
$ aai app start
Traceback (most recent call last):
  File "app.py", line 2, in <module>
    import edgeiq
  File "</usr/local/lib/python3.6/site-packages/edgeiq/__init__.py>", line 3, in <module>
  File "<frozen edgeiq>", line 7, in <module>
  File "</usr/local/lib/python3.6/site-packages/edgeiq/object_detection.py>", line 1, in <module>
  File "<frozen edgeiq.object_detection>", line 8, in <module>
  File "</usr/local/lib/python3.6/site-packages/edgeiq/base_service.py>", line 1, in <module>
  File "<frozen edgeiq.base_service>", line 11, in <module>
  File "</usr/local/lib/python3.6/site-packages/edgeiq/_model_wrapper.py>", line 1, in <module>
  File "<frozen edgeiq._model_wrapper>", line 18, in <module>
ModuleNotFoundError: No module named 'pycuda'
```

**Comment by abhatikar** [comment]
Changing to docker base image solved the issue
